### ISSUE TITLE
Handle the case when Directory does not exists, but the path looks like Directory

### ISSUE THREAD

**Issue by Konard** [linksplatform/RegularExpressions.Transformer#1]
https://github.com/linksplatform/RegularExpressions.Transformer/blob/4a8c2b3735e8d12225cc8e1619ab1a85a76617af/Platform.RegularExpressions.Transformer/TransformerCLI.cs#L29
Overwise it ends up with:
```
2>Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Code\Links\Collections.Methods\cpp\Platform.Collections.Methods\OpenDoublyLinkedListMethods.cpp'.
2>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2>   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2>   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
2>   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
2>   at Platform.RegularExpressions.Transformer.TransformerCLI.Run(String[] args, String& message)
2>   at CSharpToCppTranslator.Program.Main(String[] args) in C:\Code\Links\Collections.Methods\CSharpToCppTranslator\Program.cs:line 17
```

**Comment by Konard** [comment]
Closed by https://github.com/linksplatform/RegularExpressions.Transformer/commit/a33433a855522323095181159e181b81935a5e06
